name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build, Test, and Analyze
    runs-on: ubuntu-latest
    
    steps:
      # Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para SonarQube

      # Instalar dependencias necesarias
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential g++

      # Configurar y compilar
      - name: Configure and Build
        run: |
          cmake -S . -B build -DENABLE_TESTING=ON
          cmake --build build

      # Ejecutar pruebas
      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure

      # Análisis de SonarQube
      - name: SonarQube Analysis
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # Falla el job si la Quality Gate de SonarQube es roja
      # - name: SonarQube Quality Gate
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
